---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/8/12 15:07
---

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ------ --- --- --- --- --- --- ---
--- ngx.var.host 过滤
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ------ --- --- --- --- --- --- ---

local ignore_hosts = "," ..
        --"pubapi.kail.cn," ..
        --"m.kail.cn," ..
        ""

if ignore_hosts == nil or not (nil == string.match(ignore_hosts, "," .. ngx.var.host .. ",")) then
    return
end

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ------ --- --- --- --- --- --- ---
--- ngx.var.uri 过滤
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ------ --- --- --- --- --- --- ---

local ignore_uri = {
    kail_cn = "," ..
            --"/," ..
            "",
}

local host_key = string.gsub(ngx.var.host, "%.", "_")
local host_uri = ignore_uri[host_key]
if not (nil == host_uri) and not (nil == string.match(host_uri, "," .. ngx.var.uri .. ",")) then
    return
end

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ------ --- --- --- --- --- --- ---
--- ngx.resp.get_headers()["content-type"] 过滤
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ------ --- --- --- --- --- --- ---
-- 注意前面有个空格
local ignore_content_type = "" ..
        --" text/plain" ..
        --" application/json" ..
        ""

local content_type = ngx.resp.get_headers()["content-type"]
if not (content_type == nil) and not (nil == string.match(ignore_content_type, " " .. content_type)) then
    return
end

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ------ --- --- --- --- --- --- ---
--- 正则 过滤
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ------ --- --- --- --- --- --- ---

-- ✔️✔️✔️✔️✔️ 手机号 （中间 11 位数字，两端非数字）
local phone = "(\\D1[3-9]\\d{9}\\D)"

-- ✔️✔️✔️✔️✔️ VIN （ data-id="xxx ）（ 大写字母加数字，两端 非字母、数字、空白、/、- ）
local vin = "([^=][^A-Za-z\\s\\d/-—][A-Z\\d]{17}[^A-Za-z\\s\\d/-])"

-- ✔️✔️✔️✔️✔️ 车牌号  大写字母加数字，两端 非字母、数字、空白、/、-、款
local license = "([^A-Za-z\\s\\d/-座][A-Z][A-Z\\d]{5,6}[^A-Za-z\\s\\d/-款])"


-- 同时拼配 手机号、VIN、车牌号
local pattern = "(" .. phone .. "|" .. vin .. "|" .. license .. ")"

-- local pattern = ".*"

ngx.ctx.buffered = (ngx.ctx.buffered or "") .. ngx.arg[1];

if ngx.arg[2] then
    if ngx.re.match(ngx.ctx.buffered, pattern) then
        file = io.open("/tmp/" .. ngx.var.host .. "_" .. os.date("%Y-%m-%d_%H") .. ".log", "a+");
        local content = "<" .. ngx.var.time_local .. "> " -- 时间
                .. "<" .. ngx.var.request_uri .. "> " -- request_uri
                --.. "<" .. ngx.ctx.buffered .. ">"     -- 响应信息
                .. "<" .. string.gsub(ngx.ctx.buffered, "\n", "\\n") .. ">" -- 响应信息
                .. "<" .. phone .. "> "
                .. "<" .. vin .. "> "
                .. "<" .. license .. "> "
                .. "<" .. pattern .. "> "
                .. "<" .. content_type .. "> "
                .. "\n"
        file:write(content);
        file:close();

        -- ngx.arg[1] = "\n\n\n 疑似敏感信息，页面被禁用 " .. parrern

    end
end