---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/8/16 17:37
---

local match = ngx.re.match("http://kail.xyz", "(.+?)://(.+?)")
print(match[0])
print(match[1])
print(match[2])