---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/11/27 18:30
---
---
local basic_serializer = require "kong.plugins.log-serializers.basic"
local LogPlus = require "kong.plugins.http-log-plus.log_plus_base"

local _M = LogPlus:extend()

function _M:new ()
end

---
--- 扩充原始字段
--- ： https://github.com/Kong/kong/blob/2.0.5/kong/plugins/http-log/handler.lua
--- ： https://github.com/Kong/kong/blob/2.0.5/kong/plugins/log-serializers/basic.lua
---
function _M:log_plus(kong, ngx, conf)
    if not kong.log.serialize then
        kong.log.serialize = function()
            basic_serializer.serialize(ngx)
        end
    end

    return self.super.log_plus(kong, ngx, conf)
end

return _M